### PR TITLE
[GH-47] [FIX] Agenda item number should get updated if the items of the agenda are deleted

### LINKED ISSUE #47: Agenda item number should get updated if the items of the agenda are deleted
The agenda items' numbering gets off by one when the first item is deleted. 
The numbering is also off when the items are manually edited but might be difficult to tackle as Maria Nuñez has mentioned [here](https://github.com/mattermost/mattermost-plugin-agenda/pull/44#issuecomment-649738955)

QA Test Steps
1. Ensure that the [agenda plugin](https://github.com/mattermost/mattermost-plugin-agenda) is installed and enabled.
2. Go to a channel header and edit the agenda settings to update the hashtag if needed (e.g.: `test-Jan02`).
3. Use command `/agenda queue` to queue at least 3 items as following:
`/agenda queue item 1`
`/agenda queue item 2`
`/agenda queue item 3`
4. Click on the agenda hashtag to open up the agenda list on the RHS.
5. On the RHS, click the post menu for `item 1` (or the first item that was queued) and delete the agenda item.
6. Ensure that now there are only 2 items for that agenda hashtag: `item 2` and `item 3` on the RHS.
7. Add a new agenda item: `/agenda queue new item`.
8. Click on the hashtag to refresh the RHS.

Observed: The RHS has 3 agenda items numbered 2), 3) and 3)

Expected: The RHS has 3 agenda items numbered 1), 2) and 3)

Jira: https://mattermost.atlassian.net/browse/MM-26536

### PR DESCRIPTION
**Pull request by sanjaydemansol**
#### Summary
Fixes #47 
Now, Whenever we add new agenda item. Plugin searches for old messages for that hashtag. 
If some item is missing(deleted), it fixes numbering for all items. 

#### Testing
Ensure that the agenda plugin is installed and enabled.
Go to a channel header and edit the agenda settings to update the prefix and 
Use command /agenda queue to queue at least 3 items as following:
`/agenda queue item 1`
`/agenda queue item 2`
`/agenda queue item 3`

Click on the agenda hashtag to open up the agenda list on the RHS.
On the RHS, click the post menu for item 1 (or the first item that was queued) and delete the agenda item.
**Ensure that now there are only 2 items for that agenda hashtag: item 2 and item 3 on the RHS.**
Add a new agenda item: /agenda queue new item.
Click on the hashtag to refresh the RHS.

Outcome: The RHS has 3 agenda items numbered 1), 2) and 3)

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-agenda/issues/47
****

### CODE REVIEW

**Comment by dipak-demansol** [comment]
@sanjaydemansol LGTM

**Comment by dipak-demansol** [comment]
@sanjaydemansol i forgot to add the review so i will check it again and will add the review.

**Comment by dipak-demansol** [comment]
@sanjaydemansol @hanzei This PR is Tested From my side but i don't have pull review request for this PR, can someone send me that.

File: server/command.go [hunk 1]
```diff
@@ -132,6 +141,11 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
 		return responsef("Missing parameters for queue command")
 	}
 
+	meeting, err := p.GetMeeting(args.ChannelId)
+	if err != nil {
+		return responsef("Can't find the meeting")
```
Comment (mickmister) [inline server/command.go:146]:
```suggestion
                p.API.LogError("failed to get meeting for channel", "err", err.Error(), "channel_id": args.ChannelId)
		return responsef("No meeting was found for this channel.")
```

File: server/command.go [hunk 2]
```diff
@@ -152,20 +166,16 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
 		return responsef("Error calculating hashtags. Check the meeting settings for this channel.")
 	}
 
-	searchResults, appErr := p.API.SearchPostsInTeamForUser(args.TeamId, args.UserId, model.SearchParameter{Terms: &hashtag})
-
-	if appErr != nil {
-		return responsef("Error calculating list number")
+	numQueueItems, itemErr := calculateQueItemNumberAndUpdateOldItems(meeting, args, p, hashtag)
```
Comment (mickmister) [inline server/command.go:169]: What does `Que` mean here? Is it supposed to be `Queue`?

File: server/command.go [hunk 3]
```diff
@@ -152,20 +166,16 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
...
+	if itemErr != nil {
+		return itemErr
```
Comment (mickmister) [inline server/command.go:171]:
```suggestion
		return errors.Wrap(err, "failed to requeue items after deleting an item")
```

Comment (mickmister) [reply server/command.go:171]: Actually, `itemErr` is a `CommandResponse` right here. That's concerning since this variable name implies that this is an `error`. 2/5 `calculateQueItemNumberAndUpdateOldItems` should be returning an `error` instead of a `CommandResponse`.

File: server/command.go [hunk 4]
```diff
@@ -174,6 +184,69 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
...
+		sortedPosts = append(sortedPosts, post)
+	}
+
+	sort.Slice(sortedPosts, func(i, j int) bool {
+		return sortedPosts[i].CreateAt < sortedPosts[j].CreateAt
+	})
+
+	for _, post := range sortedPosts {
+		_, parsedMessage, _ := parseMeetingPost(meeting, post)
+		_, findErr := p.API.UpdatePost(&model.Post{
```
Comment (mickmister) [inline server/command.go:207]:
```suggestion
		_, updateErr := p.API.UpdatePost(&model.Post{
```

File: server/command.go [hunk 5]
```diff
@@ -174,6 +184,69 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
...
+func parseMeetingPost(meeting *Meeting, post *model.Post) (string, ParsedMeetingMessage, *model.CommandResponse) {
+	var (
+		prefix            string
+		hashtagDateFormat string
+	)
+	if matchGroups := meetingDateFormatRegex.FindStringSubmatch(meeting.HashtagFormat); len(matchGroups) == 4 {
+		prefix = matchGroups[1]
+		hashtagDateFormat = strings.TrimSpace(matchGroups[2])
+	} else {
+		return "", ParsedMeetingMessage{}, responsef("Error 267")
```
Comment (mickmister) [inline server/command.go:231]: What is `Error 267`?

File: server/command.go [hunk 6]
```diff
@@ -174,6 +184,69 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
...
+		})
+		counter++
+		if findErr != nil {
+			return 0, responsef("Error updating post: %s", findErr.Message)
+		}
+	}
+	return counter, nil
+}
+
+func parseMeetingPost(meeting *Meeting, post *model.Post) (string, ParsedMeetingMessage, *model.CommandResponse) {
```
Comment (mickmister) [inline server/command.go:222]: It seems like this function should be returning an `error` instead of `CommandResponse`

File: server/command.go [hunk 7]
```diff
@@ -174,6 +184,69 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
...
+	for _, post := range searchResults.PostList.Posts {
+		sortedPosts = append(sortedPosts, post)
+	}
+
+	sort.Slice(sortedPosts, func(i, j int) bool {
+		return sortedPosts[i].CreateAt < sortedPosts[j].CreateAt
+	})
+
+	for _, post := range sortedPosts {
+		_, parsedMessage, _ := parseMeetingPost(meeting, post)
```
Comment (mickmister) [inline server/command.go:206]: We should be checking for an error right here, and logging it if there is one

File: server/command.go [hunk 8]
```diff
@@ -174,6 +184,69 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
 	return &model.CommandResponse{}
 }
 
+func calculateQueItemNumberAndUpdateOldItems(meeting *Meeting, args *model.CommandArgs, p *Plugin, hashtag string) (int, *model.CommandResponse) {
+	searchResults, appErr := p.API.SearchPostsInTeamForUser(args.TeamId, args.UserId, model.SearchParameter{Terms: &hashtag})
+	if appErr != nil {
+		return 0, responsef("Error calculating list number")
```
Comment (mickmister) [inline server/command.go:190]: We should return an error here and `errors.Wrap` `appErr`

File: server/command.go [hunk 9]
```diff
@@ -174,6 +184,69 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
...
+	)
+	if matchGroups := meetingDateFormatRegex.FindStringSubmatch(meeting.HashtagFormat); len(matchGroups) == 4 {
+		prefix = matchGroups[1]
+		hashtagDateFormat = strings.TrimSpace(matchGroups[2])
+	} else {
+		return "", ParsedMeetingMessage{}, responsef("Error 267")
+	}
+
+	var (
+		messageRegexFormat = regexp.MustCompile(fmt.Sprintf(`(?m)^#### #%s(?P<date>.*) ([0-9]+)\) (?P<message>.*)?$`, prefix))
```
Comment (mickmister) [inline server/command.go:235]: I'm not verse enough in regex to gauge the stability of this. @hanzei @levb Can you take a look at this? This regex is meant to parse an agenda post's header.

@sanjaydemansol Can you please provide unit tests to assert that the code works under different circumstances?

File: server/command.go [hunk 10]
```diff
@@ -174,6 +184,69 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
...
+	matchGroups := messageRegexFormat.FindStringSubmatch(post.Message)
+	if len(matchGroups) == 4 {
+		parsedMeetingMessage := ParsedMeetingMessage{
+			date:        matchGroups[1],
+			number:      matchGroups[2],
+			textMessage: matchGroups[3],
+		}
+		return hashtagDateFormat, parsedMeetingMessage, nil
+	}
+	return hashtagDateFormat, ParsedMeetingMessage{}, responsef("An error occurred processing the meeting hashtag.")
```
Comment (mickmister) [inline server/command.go:247]: I think we should return an error that says

> failed to parse meeting post's header

File: server/command.go [hunk 11]
```diff
@@ -174,6 +184,69 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
 	return &model.CommandResponse{}
 }
 
+func calculateQueItemNumberAndUpdateOldItems(meeting *Meeting, args *model.CommandArgs, p *Plugin, hashtag string) (int, *model.CommandResponse) {
```
Comment (mickmister) [inline server/command.go:187]: It seems like this should go into a different file, because it doesn't inherently have to do with commands.

**Review by mickmister — CHANGES_REQUESTED** [review]
Great work @sanjaydemansol! I have some requests regarding error handling and writing unit tests

**Review by sibasankarnayak — APPROVED** [review]

File: server/command.go (hunk 1 above)
Comment (sanjaydemansol) [reply server/command.go]: done

File: server/command.go (hunk 2 above)
Comment (sanjaydemansol) [reply server/command.go]: changed

File: server/command.go (hunk 3 above)
Comment (sanjaydemansol) [reply server/command.go]: Right, changed.

File: server/command.go (hunk 4 above)
Comment (sanjaydemansol) [reply server/command.go]: corrected.

File: server/command.go (hunk 5 above)
Comment (sanjaydemansol) [reply server/command.go]: fixed

File: server/command.go (hunk 6 above)
Comment (sanjaydemansol) [reply server/command.go]: fixed

File: server/command.go (hunk 7 above)
Comment (sanjaydemansol) [reply server/command.go]: done

File: server/command.go (hunk 10 above)
Comment (sanjaydemansol) [reply server/command.go]: done

File: server/command.go (hunk 11 above)
Comment (sanjaydemansol) [reply server/command.go]: done

**Review by mickmister — CHANGES_REQUESTED** [review]
Thanks for implementing the changes @sanjaydemanso :+1: I have a few more comments

File: server/command.go [hunk 12]
```diff
@@ -152,20 +165,16 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
 		return responsef("Error calculating hashtags. Check the meeting settings for this channel.")
 	}
 
-	searchResults, appErr := p.API.SearchPostsInTeamForUser(args.TeamId, args.UserId, model.SearchParameter{Terms: &hashtag})
-
-	if appErr != nil {
-		return responsef("Error calculating list number")
+	numQueueItems, itemErr := calculateQueueItemNumberAndUpdateOldItems(meeting, args, p, hashtag)
+	if itemErr != nil {
+		return responsef(err.Error())
```
[the remark this answers is not in the document]
Comment (sanjaydemansol) [reply server/command.go:170]: Sure, it is done.

File: server/meeting.go [hunk 13]
```diff
@@ -61,6 +65,45 @@ func (p *Plugin) SaveMeeting(meeting *Meeting) error {
...
+			Id:        post.Id,
+			UserId:    args.UserId,
+			ChannelId: args.ChannelId,
+			RootId:    args.RootId,
+			Message:   fmt.Sprintf("#### %v %v) %v", hashtag, counter, parsedMessage.textMessage),
+		})
+		counter++
+		if updateErr != nil {
+			return 0, errors.Wrap(updateErr, "Error updating post")
+		}
```
[the remark this answers is not in the document]
Comment (sanjaydemansol) [reply server/meeting.go:102]: done

File: server/meeting.go [hunk 14]
```diff
@@ -61,6 +65,45 @@ func (p *Plugin) SaveMeeting(meeting *Meeting) error {
...
+		_, parsedMessage, err := parseMeetingPost(meeting, post)
+		if err != nil {
+			p.API.LogDebug(err.Error())
+			return 0, errors.New(err.Error())
+		}
+		_, updateErr := p.API.UpdatePost(&model.Post{
+			Id:        post.Id,
+			UserId:    args.UserId,
+			ChannelId: args.ChannelId,
+			RootId:    args.RootId,
```
[the remark this answers is not in the document]
Comment (sanjaydemansol) [reply server/meeting.go:96]: Yeah, right. Done.

File: server/meeting.go [hunk 15]
```diff
@@ -61,6 +65,45 @@ func (p *Plugin) SaveMeeting(meeting *Meeting) error {
...
+			Message:   fmt.Sprintf("#### %v %v) %v", hashtag, counter, parsedMessage.textMessage),
+		})
+		counter++
+		if updateErr != nil {
+			return 0, errors.Wrap(updateErr, "Error updating post")
+		}
+	}
+	return counter, nil
```
[the remark this answers is not in the document]
Comment (sanjaydemansol) [reply server/meeting.go:104]: done

File: server/meeting.go [hunk 16]
```diff
@@ -61,6 +65,45 @@ func (p *Plugin) SaveMeeting(meeting *Meeting) error {
...
+		return sortedPosts[i].CreateAt < sortedPosts[j].CreateAt
+	})
+
+	for _, post := range sortedPosts {
+		_, parsedMessage, err := parseMeetingPost(meeting, post)
+		if err != nil {
+			p.API.LogDebug(err.Error())
+			return 0, errors.New(err.Error())
+		}
+		_, updateErr := p.API.UpdatePost(&model.Post{
```
[the remark this answers is not in the document]
Comment (sanjaydemansol) [reply server/meeting.go:92]: done

File: server/command.go [hunk 17]
```diff
@@ -174,6 +183,34 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
...
+	matchGroups := messageRegexFormat.FindStringSubmatch(post.Message)
+	if len(matchGroups) == 4 {
+		parsedMeetingMessage := ParsedMeetingMessage{
+			date:        matchGroups[1],
+			number:      matchGroups[2],
+			textMessage: matchGroups[3],
+		}
+		return hashtagDateFormat, parsedMeetingMessage, nil
+	}
+	return hashtagDateFormat, ParsedMeetingMessage{}, errors.New("failed to parse meeting post's header")
```
[the remark this answers is not in the document]
Comment (sanjaydemansol) [reply server/command.go:211]: added

File: server/command.go (hunk 9 above)
Comment (sanjaydemansol) [reply server/command.go:199]: Added for my part, the other case is in the global scope.

File: server/meeting.go [hunk 18]
```diff
@@ -61,6 +65,53 @@ func (p *Plugin) SaveMeeting(meeting *Meeting) error {
...
 
+func (p *Plugin) calculateQueueItemNumberAndUpdateOldItems(meeting *Meeting, args *model.CommandArgs, hashtag string) (int, error) {
+	c, appErr := p.API.GetChannel(args.ChannelId)
+	if appErr != nil {
+		return 0, appErr
+	}
+	terms := fmt.Sprintf("in:%s %s", c.Name, hashtag)
+	searchResults, appErr := p.API.SearchPostsInTeamForUser(args.TeamId, args.UserId, model.SearchParameter{Terms: &terms})
+	if appErr != nil {
+		return 0, errors.Wrap(appErr, "Error calculating list number")
```
Comment (mickmister) [inline server/meeting.go:76]:
```suggestion
		return 0, errors.Wrap(appErr, "Error searching posts to find hashtags")
```

File: server/meeting.go [hunk 19]
```diff
@@ -61,6 +65,53 @@ func (p *Plugin) SaveMeeting(meeting *Meeting) error {
...
+			UserId:    post.UserId,
+			ChannelId: post.ChannelId,
+			RootId:    post.RootId,
+			Message:   fmt.Sprintf("#### %v %v) %v", hashtag, counter, parsedMessage.textMessage),
+		})
+
+		if updateErr != nil {
+			return 0, errors.Wrap(updateErr, "Error updating post")
+		}
+		counter++
```
Comment (mickmister) [inline server/meeting.go:109]: Don't feel obligated to implement this suggestion, but the newlines are meant to separate different operations. Since this `updateErr` is logically coupled with the "block" above, we don't need the newline between them. The block above actually not even a block, it's a function call with a struct. If it was an actual loop/if statement then it would make since to insert a newline after it.

Suggestion: We can remove the newline _above_ this if statement. But we should always have a newline _after_ if statements and loops. This is because after the block is finished, we are done both checking the value and processing its conditional logic. We then move on to something unrelated, thus the newline helps signal this intention.

```suggestion
		})
		if updateErr != nil {
			return 0, errors.Wrap(updateErr, "Error updating post")
		}

		counter++
```

**Review by mickmister — APPROVED** [review]
LGTM, just a few non-blocking suggestions

File: server/meeting.go (hunk 19 above)
Comment (sanjaydemansol) [reply server/meeting.go:109]: @sanjaydemansol  Thank you so much for highlighting that; I understood. Newlines are finally demystified for me.😊

File: server/meeting.go (hunk 18 above)
Comment (sanjaydemansol) [reply server/meeting.go:76]: Done

File: server/command.go [hunk 20]
```diff
@@ -132,6 +140,11 @@ func (p *Plugin) executeCommandQueue(args *model.CommandArgs) *model.CommandResp
 		return responsef("Missing parameters for queue command")
 	}
 
+	meeting, err := p.GetMeeting(args.ChannelId)
+	if err != nil {
+		p.API.LogError("failed to get meeting for channel", "err", err.Error(), "channel_id:", args.ChannelId)
```
[the remark this answers is not in the document]
Comment (sanjaydemansol) [reply server/command.go:145]: done

**Comment by hanzei** [comment]
@dipak-demansol This is ready for review

**Review by dipak-demansol — APPROVED** [review]
**LGTM** Tested it in the Chat and Thread Section.

**Review by hanzei — APPROVED** [review]
